# -*- mode: ruby -*-
# vi: set ft=ruby : 
Vagrant.configure("2") do |config|
config.vm.box = "kalilinux/rolling"
config.vm.network "private_network", ip: "192.168.56.10"
config.vm.boot_timeout = 600
end